### ISSUE TITLE
Support for more than 60 FPS

### ISSUE THREAD

**Issue by FoxelFox** [munrocket/gl-bench#8]
The Chart Y-Axis and colors should be based on Display refresh rate.

![image](https://user-images.githubusercontent.com/1883860/66420531-50ee2b00-ea06-11e9-92f5-1763785326f8.png)

From what i know it is not possible to get the browsers refresh rate yet. The only solution would be to measure the time between requestAnimationFrame Calls.

**Comment by munrocket** [comment]
Thanks for feedback and first issue! I need to figure out best solution for this problem. Look like it is possible to start rAF loop before initialization and close it after 3 frames to get maximum. Also we can achieve 200+FPS on any PC where we off vsync in browser.

**Comment by munrocket** [comment]
Check please.

**Comment by FoxelFox** [comment]
@munrocket looks good
![image](https://user-images.githubusercontent.com/1883860/66489001-2e641c80-eaaf-11e9-8441-60ac41e5a0fe.png)

**Comment by munrocket** [comment]
Nice.
